name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.17' ]

    steps:
    - name: Checkout project
      uses: actions/checkout@v3.0.2

    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/fatih/set
        go get -u github.com/relvacode/iso8601
        go get -u github.com/spf13/cobra

    - name: Run build
      run: go build .

    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Run testing
      run: go test -v
